services:
  php-fpm:
    image: tech-test
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - "APP_ENV=dev"
        - "XDEBUG=1"
    volumes:
      - "./code:/code"
      - "./docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
    restart: always
    networks:
      - docupet-test-network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        - "APP_ENV=dev"
    ports:
      - "8088:80"
    volumes:
      - "./code/public:/code/public"
    depends_on:
      - php-fpm
    restart: always
    networks:
      - docupet-test-network

  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_DATABASE: 'docupet_db'
      MYSQL_USER: 'docupet'
      MYSQL_PASSWORD: 'password'
    ports:
      - '33077:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - docupet-test-network

  node:
    image: node:alpine
    working_dir: /srv/app
    ports:
      - "8888:8000"
    entrypoint: /bin/sh
    volumes:
      - type: bind
        source: ./code
        target: /srv/app
    tty: true
    networks:
      - docupet-test-network

networks:
  docupet-test-network:
    driver: bridge

volumes:
  mysql-data:
